const houseOffer = [
  {
    numer: "7a",
    status: "Dostępny",
    linkDoOferty: "#houses",
    metraz: 54.21,
    pokoje: 3,
    cena: 598519,
    poziom: "parter",
    ogrodek: 38.41,
    x: 38,
    y: 19,
  },
  {
    numer: "8a",
    status: "Dostępny",
    linkDoOferty: "#houses",
    metraz: 54.21,
    pokoje: 3,
    cena: 598519,
    poziom: "parter",
    ogrodek: 38.41,
    x: 40,
    y: 25,
  },
  {
    numer: "9a",
    status: "Dostępny",
    linkDoOferty: "#houses",
    metraz: 54.21,
    pokoje: 3,
    cena: 598519,
    poziom: "parter",
    ogrodek: 38.41,
    x: 50,
    y: 40,
  },
  {
    numer: "10a",
    status: "Dostępny",
    linkDoOferty: "#houses",
    metraz: 54.21,
    pokoje: 3,
    cena: 598519,
    poziom: "parter",
    ogrodek: 38.41,
    x: 55,
    y: 50,
  },
];

export default houseOffer;
